version: '3.4'

services:
  back:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
    ports:
      - "5000:80"

  front:
    ports:
        - "5001:3000"
    
  proxy:
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"
 
  db: 
    environment:
      - MSSQL_SA_PASSWORD=Roman221510
      - ACCEPT_EULA=Y
    ports:
        - "1433:1433"  
    volumes:
        - ./SQLData/data:/var/opt/mssql/data
        - ./SQLData/log:/var/opt/mssql/log
        - ./SQLData/secrets:/var/opt/mssql/secrets